kube_apiserver_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kube-apiserver"
kube_controller_manager_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kube-controller-manager"
kube_scheduler_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kube-scheduler"
kubernetes_cluster_ip_range: "10.32.0.0/24"
kubernetes_cluster_cidr: "10.200.0.0/16"
