---
- name: Show us the kubeconfig we're creating
  debug:
    msg: "Creating kubeconfig: {{ kubeconfig_name }}"

- name: Ensure certificate authority is present.
  stat:
    path: "{{ certificate_authority_certificate_location }}/ca.pem"
  failed_when: False

- name: Create kubeconfig
  shell: "kubectl config {{ item }} --kubeconfig={{ kubeconfig_location }}/{{ kubeconfig_name }}.kubeconfig"
  register: kubectl_result
  failed_when: kubectl_result.rc != 0
  with_items:
    - "set-cluster {{ cluster_name }} --certificate-authority={{ certificate_authority_certificate_location }}/ca.pem --embed-certs=true --server={{ kubernetes_control_plane_server }}"
    - "set-credentials {{ user }} --client-certificate={{ client_certificate }} --client-key={{ client_key }} --embed-certs=true"
    - "set-context default --cluster={{ cluster_name }} --user={{ user }}"
    - "use-context default"

- name: Verify that the kubeconfig was created
  stat:
    path: "{{ kubeconfig_location }}/{{ kubeconfig_name }}.kubeconfig"
  failed_when: False
